### ISSUE TITLE
!proxy gives error 404 or need to edit privacy policy

### ISSUE THREAD

**Issue by GamerM** [duckduckgo/duckduckgo#111]
Hello.I was looking through the privacy policy for no reason and saw that there is a !bang for a free proxy. I try to use it by typing !proxy [domain name], but it didn't work. It gives error 404 to GitHub. Can you guys fix the problem or edit the policy if you're not using that !bang anymore. Thanks!

This is what it gives me: http://nodeunblocker.com/proxy/no-js?url...

**Comment by lgriner** [comment]
it looks like they've disabled service for now (aup violation). post on site:
> The proxy is currently disabled because someone used it to violate Nodejitsu's AUP. Not sure when it > will be back online, but it might take a while.

**Comment by moollaza** [comment]
Thanks for reporting. I'll make a task to remove the proxy !bang.

**Comment by moollaza** [comment]
We've removed the !proxy bang.
