### ISSUE TITLE
Duckpan doesn't show any results or container 

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/duckduckgo#116]
I was trying to fix the alignment of the result with the search results in https://github.com/duckduckgo/zeroclickinfo-goodies/pull/833#issuecomment-72973713 raised by @chrismorast which is actually really awkward to do on duckpan server.

I was thinking we should have duckpan show some randomly generated search-like content (lorem ipsum maybe) so that users can actually check the alignment against the search results etc.

cc @MrChrisW @moollaza @chrismorast

**Comment by mintsoft** [comment]
Not sure if this is actually the right repo for this, should it be https://github.com/duckduckgo/p5-app-duckpan instead?

**Comment by MrChrisW** [comment]
@mintsoft Sounds like a good improvement, I've seen the request "align with SERP content" a few times. Regarding which is the right repo, guessing this is internal as DuckPAN actually pulls the `page_root.html` directly from duckduckgo.com like so https://duckduckgo.com/?q=duckduckhack-template-for-spice2

**Comment by moollaza** [comment]
>Not sure if this is actually the right repo for this, should it be https://github.com/duckduckgo/p5-app-duckpan instead?

Yup, that's a better place for an issue like this, but it's no prob. This poor repo gets no love.

>I was thinking we should have duckpan show some randomly generated search-like content (lorem ipsum maybe) so that users can actually check the alignment against the search results etc.

@mintsoft that's a great idea! After a bit of messing around I think I've found a way to inject a fake ad and some results into the SERP. I'll have a PR soon!

**Comment by mintsoft** [comment]
Fixed by @moollaza in the correct repo here: https://github.com/duckduckgo/p5-app-duckpan/pull/219
