### ISSUE TITLE
language forced when using !g bang

### ISSUE THREAD

**Issue by yhu420** [duckduckgo/duckduckgo#120]
Hello,
It's been a while since I've begun using duckduckgo, and I just might stop using it only because of one small frustrating thing. English is not my native language, but I have to look for things in english very often. Therefore I often use the !g bang to look for thing both in french and in english. 
Now comes the issue: Duckduckgo always puts &hl=fr in the google requests, so I everytime have to remove it manually. The perfect fix would be to simply delete it permanently. Is there an issue to remove it in the options, and if not is it possible to do something about it?
Thank you very much

**Comment by mintsoft** [comment]
Hello @yhu420 thanks for the report! I'm not sure what the ideal behavior would be in your particular situation however I've just been playing with how this works, it depends on the location setting:
![image](https://cloud.githubusercontent.com/assets/978048/6427108/40e97006-bf6e-11e4-9696-5963ea687d47.png)

With `!g` it'll append the language detected by GeoIP or as you've chosen in the location settings; one option to give you better control over the language used would be to specify which google you want. I.e. for English there're `!gus` and `!guk` (US or UK) or for french there's `!gfr`. Does that help at all?

**Comment by yhu420** [comment]
You have a typical developer mind, as well as many other people including me ;) trying to make workarounds when the solution is right there. why make more bangs? Google automatically detects the language depending on many other factors: location, terms used, and if you're logged in, it knows you by heart. The simplest solution would be imo to simply delete the "&hl=" so google would automatically deduce the language, and trust me, it never fails.
Otherwise, a setting to disable it in options menu would do it to avoid complaints from other people.
Thank you for reading anyway, and have a good day

**Comment by mintsoft** [comment]
Ah I see, so you'd like !g to default to specifying no `&hl=` attributes. @jagtalon @moollaza any thoughts on why this passes the location settings through?

**Comment by yhu420** [comment]
Indeed, this is what I think would be the easiest fix for this issue, by the way, I've never seen such a quick support on the internet, good job all of you ;)

**Comment by mintsoft** [comment]
@yhu420 It's what we do :)

**Comment by moollaza** [comment]
@yhu420 apologies for the frustrations!

@mintsoft I'm not too sure about the `hl` setting and region toggle. I'll make a task for the team to investigate this further though!

**Comment by moollaza** [comment]
@yhu420 to clarify, as far as I can tell, the `hl` parameter only modifies the interface language for Google, so the Google's UI will match the searcher's browser or region setting language.

Are you saying it's also modifying the results? Or at you saying you just always want Google's interface to be in English?

**Comment by yhu420** [comment]
It definitely does not only change the interface.
"Pain" is a word which means "bread" in french, and .. pain in english.
Try inputting "pain !g" with and without the localization setting. Personnally, I got two completely different result lists.
Thank you for the support.

**Comment by mintsoft** [comment]
@moollaza for me I found it changed the results with different regions set. I don't really understand why we're injecting our locale detection into Google. Surely "the big G" would just work it out if we didn't specify anyway?

**Comment by moollaza** [comment]
@yhu420 @mintsoft spoke with the team, we'll be removing the `hl` param from Google !bangs.

**Comment by yhu420** [comment]
Wow, never seen such a quick team and great support! Thanks all of you ;)

**Comment by moollaza** [comment]
The fix will be merged and released shortly

**Comment by jdorweiler** [comment]
@yhu420 this should be fixed now.  The !g bang only sets a  language if you have chosen one from the settings page.

**Comment by yhu420** [comment]
@jdorweiler You guys are amazing :) Thank you again for the support!

**Comment by jdorweiler** [comment]
@yhu420 Thanks! :cake:
