### ISSUE TITLE
!verb bang does not work anymore

### ISSUE THREAD

**Issue by aseure** [duckduckgo/duckduckgo#121]
Hello,

For a few days now, the `!verb` bang is broken. It currently redirects towards [Rapid Languages](https://rapidlanguages.com/) which doesn't handle the request, regardless of the language.

Trying to request `!verb sing` for instance, I'm redirected [here](https://rapidlanguages.com//en/Verb-sing).

**Comment by jdorweiler** [comment]
What's the correct url that it should be using?

**Comment by aseure** [comment]
DuckDuckGo previously redirected towards [Verbomatic](http://verbomatic.com/) but that domain name now points to [RapidLanguages](https://rapidlanguages.com/), which doesn't handle conjugation.

A good change/alternative IMHO should be to request the [Reverso conjugator](http://conjugator.reverso.net/) since their API seems really straightforward. For instance, *!verb sing* could redirects to [http://conjugator.reverso.net/conjugation-english-verb-dance.html](http://conjugator.reverso.net/conjugation-english-verb-sing.html).

**Comment by jdorweiler** [comment]
Looks like a better source to me too.   I'll make the update and ping you here when it's live.

**Comment by aseure** [comment]
Ok great!

**Comment by aseure** [comment]
By the way, I'd like to add that the `!verb` bang is a short version of the `!verbomatic` bang. The last one has no more sense if the redirection changes from Verbomatic to Reverso conjugator.

**Comment by jdorweiler** [comment]
Ok, thanks!  I'll update that one too.

**Comment by jdorweiler** [comment]
@aseure  https://duckduckgo.com/?q=!verb+sing
