### ISSUE TITLE
implement https-everywhere in search results

### ISSUE THREAD

**Issue by J0WI** [duckduckgo/duckduckgo#145]
Would be great to use https links whenever possible, not just for Wikipedia. E.g. results to YouTube are still linked over http.
A way to implement this could be this project: https://github.com/grindhold/libhttpseverywhere

**Comment by moollaza** [comment]
@J0WI this is a great suggestion! But actually, we are already using HTTPS Everywhere (for over 2 years now!) as you can see here: https://duck.co/blog/https-on-by-default

Can you give me some examples of sites with SSL that we're sending you to via HTTP?

**Comment by moollaza** [comment]
BTW, this post is probably better suited for our Community Platform. This repo is actually responsible for the Instant Answer platform, not the DDG Site itself, but I don't blame you as that isn't very clear ;)

**Comment by J0WI** [comment]
STR: type 'youtube' in DDG (ger).
first result: Instand answer from Wikipedia, linked to http://r.duckduckgo.com/l/?kh=-1&uddg=http%3A%2F%2Fde.wikipedia.org%2Fwiki%2FYouTube
seccond result: youtube.com, linked to http://r.duckduckgo.com/l/?kh=-1&uddg=http%3A%2F%2Fwww.youtube.com%2F

**Comment by J0WI** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1145194

**Comment by moollaza** [comment]
@J0WI I'm not seeing any HTTP links to YouTube here: https://duckduckgo.com/?q=youtube&t=ffab&ia=about&iax=1

Please provide a link (or img?) so I know we're looking at the same thing.

**Comment by J0WI** [comment]
https://duckduckgo.com/?q=site%3Ayoutube.com
all links are http.

**Comment by fossterer** [comment]
This is no more relevant. All the links provided above as evidence to "non-HTTPS" results are now leading to  HTTPS results.

I vote to close this issue.

**Comment by mintsoft** [comment]
@fossterer @J0WI I've just checked the links as mentioned, all are https. If this is in error please feel free to reopen this issue with an example :+1:
