### ISSUE TITLE
Query breaks the page!

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/duckduckgo#167]
querying for `sc OpenSCManager FAILED "1747"` appears to break the JS:

![image](https://cloud.githubusercontent.com/assets/978048/11684188/b6063c9c-9e67-11e5-96a7-40163faae400.png)

**Comment by mintsoft** [comment]
![image](https://cloud.githubusercontent.com/assets/978048/11684197/c7e21472-9e67-11e5-8b77-ef6c70cddcf5.png)

**Comment by moollaza** [comment]
@mintsoft thanks! We're about to roll out a fix :+1:
