### ISSUE TITLE
Currency Conversions

### ISSUE THREAD

**Issue by Ntrails** [duckduckgo/duckduckgo#171]
Typing in "GBP/ZAR" doesn't return the currency rate in the way "GBP ZAR" does, though the former is more typical phrasing?  Is it possible to parse the forward slash for this?

(Either way it's a cool feature so thanks)

**Comment by mintsoft** [comment]
Thanks for the report @Ntrails I've moved this issue into the repo where this IA lives: https://github.com/duckduckgo/zeroclickinfo-spice/issues/2398
