### ISSUE TITLE
Feature request: Add MathJax library

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/duckduckgo#176]
For support of mathematic formulae, e.g. in math cheat sheets and geometry IA.
See https://www.mathjax.org/
Suggested by @sekhavati

**Comment by moollaza** [comment]
@tagawa @sekhavati we currently have a similar library that allows the display of Math which we're using for the Symbolab IA. It's called Mathquill: http://mathquill.com/

I previously investigated MathJax and the library is simply too large so we decided not to use it.

Mathquill should work though, but it would require modifying the way cheat sheets work: we'd need a new template that expects to have plaintext and/or LaTeX content which would need to be converted to HTML using the MathQuill JS and CSS (which we only want to load when needed).

@sekhavati do you have a math cheat sheet in mind? Would you like to submit a new template and a new IA (separately) so we can test it out?

**Comment by tagawa** [comment]
That sounds fine. I'm not aware of a cheat sheet needing this at the moment but there was a user wanting to make a trigonometry cheat sheet which would need math notation.

**Comment by GuiltyDolphin** [comment]
@tagawa @moollaza: There's been a few PR's lately which use mathematical notation - I think properly formatted mathematical cheat sheets would be dandy!

**Comment by sekhavati** [comment]
@moollaza I haven't got an immediate use for it myself. I suggested it as an option to address [Spice#2113](https://github.com/duckduckgo/zeroclickinfo-spice/issues/2113).

**Comment by Owlree** [comment]
Reviving this.

Hello! This is my first post here. I am a programmer, but with heavy mathematics background, and I stumbled across DuckDuckGo some time ago and now this issue. I think it would be a good idea to have high school level mathematics cheat sheet, as they are heavily used by students many students. We could use Mathquill for this.

**Comment by tagawa** [comment]
Hi @Owlree. Good idea. We have a few maths-related cheatsheets, e.g. [geometry cheatsheet](https://duckduckgo.com/?q=geometry+cheatsheet&iax=1), but a general one would be helpful. I've copied your comment to a new issue: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3914
