### ISSUE TITLE
matched_trigger sometimes wrong with "any" triggers

### ISSUE THREAD

**Issue by zachthompson** [duckduckgo/duckduckgo#177]
When using an `any` trigger and the trigger word appears in the middle of the query, `matched_trigger` does not work.  Using `DDG::Goodie::Week` to test, with the trigger `week`:

```
Query: what week of the year
  You entered: what week of the year
remainder: what of the year, query_raw: what week of the year at /home/zach/duckduckgo/lib//DDG/Request.pm line 258.
matched_trigger: what week of the year at /home/zach/duckduckgo/lib//DDG/Request.pm line 260.
```

**Comment by GuiltyDolphin** [comment]
@zachthompson Just to clarify the spec here, is this correct for what the remainder should be for each of the following (if not, please do correct me!)?

```perl
triggers => 'foo';

'foo bar' -> 'bar';
'bar foo' -> 'bar';
'bar foo bar' -> 'bar bar';
'bar foo foo bar' -> 'bar foo bar';
'foo bar foo' -> 'bar foo';
'foo foo' -> 'foo';
'foo' -> '';
```

So, is it correct that we will always use the *first* occurrence as the trigger? And priority-wise, should we do a full check of `start`, `end`, and `startend` before we check `any`?

@zachthompson By the way, I've had a bit of a look through and I'm not entirely clear on *where* the processing happens, [here](https://github.com/duckduckgo/duckduckgo/blob/master/lib/DDG/Block/Words.pm#L214), maybe [here](https://github.com/duckduckgo/duckduckgo/blob/master/lib/DDG/Block/Words.pm#L270)?

Could you give me a bit of a rundown on why we don't just normalize the string then grab the first occurrence with a regex and split (we can use LIMIT) on that to obtain the various components of the query?
