### ISSUE TITLE
Feature request: Image search (via TinEye)

### ISSUE THREAD

**Issue by Translator5** [duckduckgo/duckduckgo#184]
There is a Firefox Plugin named TinEye, it is very useful for searching images.
May it is possible to build in the search system into Duck'y?

**Comment by moollaza** [comment]
@Translator5 hey there, thanks for the suggestion.

We've discussed adding a TinEye integration before and it's still something we're considering. However the TinEye API is a paid API so we don't have any immediate plans to use it.

Thanks!
