### ISSUE TITLE
Join Duck Duck GO

### ISSUE THREAD

**Issue by jonathandalloo** [duckduckgo/duckduckgo#185]
GitHub ID - @jdalloo

**Comment by moollaza** [comment]
@jdalloo thanks, mind moving your comment over to https://github.com/duckduckgo/duckduckgo/issues/182?

**Comment by zekiel** [comment]
sent an invite to you @jdalloo  Should be able to accept it here: https://github.com/orgs/duckduckgo/teams/duckduckhack-contributors

**Comment by jdalloo** [comment]
link does not work. :)

**Comment by moollaza** [comment]
@jonathandalloo you sure? Works for me..

**Comment by Asternitix** [comment]
having trouble as well with link. please fix.

**Comment by moollaza** [comment]
> having trouble as well with link. please fix.

@Asternitix are you having trouble with https://github.com/orgs/duckduckgo/teams/duckduckhack-contributors?

Can you describe the issue?

**Comment by zekiel** [comment]
@jonathandalloo you are a member so seems to have worked in the interim
@Asternitix  just sent you an invite so it probably wasn't sent before. Please reopen if you're still having troubles.

**Comment by midopooler** [comment]
I also want to join it. @moollaza @zekiel

**Comment by moollaza** [comment]
Thanks for offering @midopooler but unfortunately DuckDuckHack is now in maintenance mode and we’re not adding new members.
