### ISSUE TITLE
Programming IA

### ISSUE THREAD

**Issue by rockerest** [duckduckgo/duckduckgo#188]
Hi,

Thanks for DDG! I use it every day.

I'd like to get involved and help out, but my Programming IA of choice (JavaScript) has stumped me for a second. I figured I'd ask instead of trying to blindly bump around.

On the [wiki page](https://github.com/duckduckgo/duckduckgo/wiki/Programming-IA-Coverage) it lists "JavaScript Package/library lookup" as needing a developer. I thought I'd integrate NPM, but swore it's already been done. Sure enough - it's integrated under "NodeJS".

I think I speak for the majority of JS devs when I say that NPM is the _de facto_ package/library repository for all of JavaScript. It has eclipsed every other package manager in basically every way.

Was there an intention for a different kind of package manager for JavaScript, or does the "NodeJS" row cover JavaScript, too? (It does, in my opinion).

For reference, there is no standard library _per se_ to reference (and besides, MDN - the closest we have to a standard library reference - is already an IA).

**Comment by zekiel** [comment]
@rockerest  Thanks for the support and especially for getting involved. As is, there aren't many hard requirements outside the API response time and the source itself being the best possible. That last bit is qualitative and exactly what we're relying on the community ensure. 
If you want to modify any current IAs, feel free to ping the Maintainer or just go ahead and make the PR if there is none. I think we'd all be happy for better, more expansive JS coverage :)
