### ISSUE TITLE
More Test Languages + Locations

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/duckduckgo#189]
We should _at least_ have a test language for each of the locations we have. It would be good if we could have a few more locations as well, using different scripts, at least _every_ continent, etc.

We should also add the United Kingdom, it shares some things in common with the US (language, for the most-part), but has some differences that are useful in testing such as how dates are handled.

**Comment by mintsoft** [comment]
Agreed! :gb:
