### ISSUE TITLE
Add syntax highlighting for code snippets

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/duckduckgo#190]
For example, in programming IAs like this:

<img width="350" alt="ddg-code-snippet" src="https://cloud.githubusercontent.com/assets/94173/14872095/dc3c7f86-0d23-11e6-84e5-1f6e3af877a5.png">

(Suggested in the [Java subreddit](https://www.reddit.com/r/java/comments/4gqudt/improving_duckduckgos_javarelated_searches/d2k0per))

**Comment by moollaza** [comment]
This has been implemented 👍
