### ISSUE TITLE
Add "copy" button for certain Instant Answers

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/duckduckgo#191]
For example, the shruggie IA, code snippets, complex names and spellings, etc. could benefit from being able to easily copy and paste them. With the [clipboard API](https://www.w3.org/TR/clipboard-apis/) this should be possible in some browsers.

Originally [suggested on Twitter](https://twitter.com/abditum/status/725589318891261953).

**Comment by GuiltyDolphin** [comment]
@tagawa I can imagine this being an automatic feature for IAs using the `text` template - or perhaps as an additional option? `text_copy => 1` kind of thing.
