### ISSUE TITLE
Add support for Dynamex carrier tracking numbers

### ISSUE THREAD

**Issue by scottlinux** [duckduckgo/duckduckgo#193]
Amazon same-day delivery uses a carrier service https://www.dynamex.com/ 

Is it possible to add a search for an Dynamex tracking number to go to the Dynamex tracking page similar to FedEx/UPS/USPS tracking numbers?

Example tracking no:

DXARDU0088670

**Comment by moollaza** [comment]
@scottlinux we currently have a [Package Tracking](https://duck.co/ia/view/package_tracking) Spice Instant Answer which should handle Dynamex tracking numbers.

We're using data from https://PackageTrackr.com

However, it looks like that PackageTrackr might be having some issues with Dynamex packages right now. For this package, DXAMZE0151543, Dynamex has data, but PT displays a message that the data isn't available yet.

Once PackageTrackr is working correctly, we'll be able to support Dynamex packages again 👍
