### ISSUE TITLE
Dear DuckDuckGo team

### ISSUE THREAD

**Issue by yonas** [duckduckgo/duckduckgo#197]
Hello DuckDuckGo team,

I wasn't sure how to properly contact the DuckDuckGo team, so I'm writing here. Please let me know if there's a more appropriate place to communicate my concerns.

Regarding the Yandex project named "Cocaine":

https://github.com/cocaine

I just had a discussion with the Yandex team, and the original author, [Andrey Sibiryov](https://github.com/kobolog):

https://github.com/cocaine/cocaine-core/issues/258#issuecomment-219289922

It turns out they are actually trying to legitimize the abuse of cocaine "so that people have more freedom of choice in ways to kill themselves". From Andrey Sibiryov:

> Hey Yonas,
> 
> All drugs should be legal and accessible, so that people have more freedom of choice in ways to kill themselves, which, unfortunately, is limited now to alcohol, tobacco and sugar, in most countries.
> 
> But rejoice! Some liberal governments already realized the downsides of these overly restrictive policies, and now allow and sometimes even provide such things as marijuana (e.g. certain states of the US, Netherlands and so on) or plain euthanasia (e.g. Belgium, Ireland and much more) for their citizens.
> 
> So I'm gonna lock this thread down until cocaine is legal again and then come back and publicly shame you for your bigoted and small-minded world views that you tried to impose on others here.
> 
> Now, go and do something useful for the world, Yonas.

All this on GitHub, which is publicly accessible to young people struggling to fight off peer pressure to abuse cocaine.

And if you haven't seen the project page, it quotes a song that talks about abusing cocaine:

>       If you wanna hang out you've got to take her out; cocaine.
>       If you wanna get down, down on the ground; cocaine.
>       She don't lie, she don't lie, she don't lie; cocaine.
>             -- J. J. Cale, cover version by Eric Clapton

Is this the type of company we want to be associated with? Does DuckDuckGo still want to be associated with such a company?

I'm sure the users of DuckDuckGo would appreciate a public explanation of why DuckDuckGo continues to partner with a company that wants us to kill ourselves on cocaine.

Have a great day.

Cheers,
Yonas

**Comment by tagawa** [comment]
Thank you for making us aware of this @yonas. I'll forward it internally. Regarding contacting the DuckDuckGo team, we have an open@duckduckgo.com email address which we try to reply to within a few days.

**Comment by nilnilnil** [comment]
We're sorry about how that issue turned out @yonas. That's a pretty unnecessary response.

While DuckDuckGo does partner with Yandex for search results, we are not at all affiliated with that project. We work with hundreds of sources to create our SERP. You can read more about that here: https://duck.co/help/results/sources.
