### ISSUE TITLE
Search beginning with the word 'html'

### ISSUE THREAD

**Issue by Neats29** [duckduckgo/duckduckgo#198]
Not sure where is the best place to raise this but I've noticed that when I type a word beginning with 'html' into the chrome search bar, unlike every other search where I'm taken to the results page on duckduckgo, I get redirected to the https://duckduckgo.com/ page where I have to search my query again. I've only found this behaviour when my search starts with the word html. Also once I search on the https://duckduckgo.com, I am taken to what seems to be an old version of the DDG results page. 

Is this a bug that you guys are aware of?
Thanks

**Comment by GuiltyDolphin** [comment]
@Neats29 It sounds like you are being redirected to the HTML-only version of the site; I'm not having the same issue on Firefox so it's entirely possible that you have `html` set up as a keyword for the HTML-only version (similar to having `duckduckgo ...` redirect to DuckDuckGo). If you look under your search engine settings you should be able to find out.

**Comment by edgesince84** [comment]
hey @Neats29 
Are you still having this issue?  I think @GuiltyDolphin is spot-on with his advice. Please let me know- we're closing up old PRs and issues in the next week.

If you're interested in working on something new, we'd like to invite you to our [new forum](https://forum.duckduckhack.com/) to preview how we're improving programming-related searches. There are a lot of important tasks up for grabs that we'd like your help with, so feel free to and [jump in](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53).

**Comment by Neats29** [comment]
@edgesince84 I didn't find html being set up as a keyword anywhere. But at least I know why it's happening.

thanks.
