### ISSUE TITLE
What is the purpose of `zci answer_type`?

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/duckduckgo#200]
I've had a look through the repo (and DuckPAN, platform etc.); and it doesn't look like `answer_type` is used for anything?

My previous assumption was that it was some form of ID specifier - but as @mintsoft noticed, the ID and `answer_type` don't always match up.

@zachthompson Is there something internal going on here? Or can we remove it?

/cc @moollaza

**Comment by GuiltyDolphin** [comment]
@zachthompson Hmm... Looking closer it looks like something to do with production? Why do we need the `answer_type` rather than just using the metadata to link packages?

**Comment by moollaza** [comment]
I think it's an artifact of the original API and it's still used by the DuckDuckGo API.

I'm not sure if we use it internally anywhere, but I don't think so.

**Comment by GuiltyDolphin** [comment]
@moollaza Could we instead add the ID to the response automatically, at a later stage - so we don't have to specify an 'answer_type' which seems inconsistent anyway?
