### ISSUE TITLE
Add a `remainder_non_empty` handler

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/duckduckgo#201]
I see a lot of IAs that do `handler remainder => sub { my $query = $_; return unless $query; ... }` which will exit the handler early for *any* falsey Perl value. What people really want is `return if $query eq ''`.

We should come up with a solution to this - either by *strongly* enforcing the use of `return if $query eq ''`, adding a handler that will deal with this case automatically, or some other magic. I doubt we can convince the Perl team to add a boolean type :wink:

/cc @mintsoft @moollaza @zachthompson

**Comment by zachthompson** [comment]
There is no reason to check for an empty string.
```Perl
return;
```
and
```Perl
return unless $_;
```
and
```Perl
if($_){
    do_stuff and return  
}
```
and
```Perl
return if $_ eq ''
```
all have the same effect of returning undefined if the remainder is "empty".  It's really not worth more attention than that.

I think it's partially due to our bad example handler.
```Perl
handle remainder => sub {
    return $_ if $_;
    return;
};
```
This is exactly the same as
```Perl
handle remainder => sub {
    return $_;
};
```
which is a totally useless method.  Needs to be updated.  The `return unless $_;`, otherwise process form is totally fine.

**Comment by GuiltyDolphin** [comment]
@zachthompson `return unless $_` will also return if the remainder is '0' due to the way Perl handles truthiness; this is the case I am referring to - people using `return unless $_` as a guard against no remainder also guards against a 'falsy' remainder.

**Comment by zachthompson** [comment]
How many IAs do we have that need to distinguish that?  I don't think enough that we should worry about a new handler type.

**Comment by GuiltyDolphin** [comment]
@zachthompson Yeah - I've said before I'm bad at these PR titles :wink: - I'm just looking for a general solution/ideas.

Maybe the best thing to do is just ensure the docs are explicit and keep things updated where we can? (It's mostly a concern for IAs that deal with numeric queries).

**Comment by zachthompson** [comment]
@GuiltyDolphin The docs could definitely stand a quick update.

**Comment by GuiltyDolphin** [comment]
@zachthompson I've clarified the docs a bit; I think we're sorted on what we're going to do here so this is resolved!
