### ISSUE TITLE
Text overflows from UI boxes

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/duckduckgo#202]
**Steps to reproduce:**
1. Perform a search with the UI set to Russian, e.g.
https://duckduckgo.com/?q=soundcloud+surfing+girl&kad=ru_RU
2. Open the IA attribution box and the region selector.

**What should happen:**
All text should be contained within their respective boxes.

**What actually happens:**
Some text overflows the boxes. See screenshots below.
Thanks to @kirllos for the initial report.

![attribution-overflow](https://cloud.githubusercontent.com/assets/94173/15505787/ef2031d8-21ff-11e6-99d1-02808ee53b4b.png)
![attribution-overflow2](https://cloud.githubusercontent.com/assets/94173/15505788/ef20537a-21ff-11e6-87de-c946359aa74c.png)

**Comment by tagawa** [comment]
Also seems to happen for Greek: https://duck.co/forum/thread/20591/duckduckgo-design-problem

**Comment by bsstoner** [comment]
@moollaza please make a task for this

**Comment by tagawa** [comment]
Thanks @bsstoner - done.

**Comment by tagawa** [comment]
Also happens for Spanish on mobile: https://github.com/duckduckgo/duckduckgo/issues/203

**Comment by matheusagcosta** [comment]
This fix the region selector

```
.frm__input:focus ~ .modal__header__clear.sep--before.js-region-filter-clear {
    opacity: 0;
    visibility: hidden;
}

```

**Comment by rajamanojkumar** [comment]
@tagawa Can I work on this issue..?

**Comment by moollaza** [comment]
Thanks for offering @rajamanojkumar but it looks like this is actually fixed :)

Unfortunately the code for that is internal so it would need to be fixed by a staff member.
