### ISSUE TITLE
Text bug on mobile (Bugs en textos - version movil)

### ISSUE THREAD

**Issue by Che234** [duckduckgo/duckduckgo#203]
**English:**
In the attached screenshot using Chrome, have a 320px resolution shows text overflowing in the region selection dialog box.

**Spanish:**
Buenas aquí envió una captura de pantalla con chrome, revisando la resolución 320px y encontré que los textos se sobre ponen en la selección de idiomas con las imágenes de los países.
![filtro por region](https://cloud.githubusercontent.com/assets/5543449/15660460/d024e4e0-26aa-11e6-8551-b91c7e75e729.png)

**Comment by tagawa** [comment]
Gracias @Che234. We have a similar bug report here: https://github.com/duckduckgo/duckduckgo/issues/202#issuecomment-222392917 so I'll close this and inform the design team.
(Sorry, I can't speak Spanish)

**Comment by Che234** [comment]
Do not worry , I do not speak English well . I always like to help project like this succeed
