### ISSUE TITLE
Spice: 'Refactor' Spice tests

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/duckduckgo#205]
Currently it seems that the Spice tests contain mostly redundancy - getting in the way of testing the actual triggering, for example:

``` perl
'query' => test_spice(
    '/js/spice/id/...',
    call_type => 'include',
    caller => 'DDG::Spice::...'
)
```

I think really this should be something more like:

``` perl
'query' => test_spice('share_sub')
```

where `'share_sub'` is the path to append to `share/spice/id/...`.

I think if we pulled this out people might be more inclined to include _more_ tests, as there would be less _resistance_ to adding new tests.

Any thoughts @moollaza @zachthompson ?

By the way, it looks like pretty much 99% of Spice use 'include', I think we can probably default to that unless 'self' is specified?

/cc @duckduckgo/community-leaders

**Comment by gaulrobe** [comment]
I will always 👍 an idea for avoiding redundancy.

**Comment by moollaza** [comment]
I don't have any objects, just makes everything simpler 👍

**Comment by mintsoft** [comment]
Yeah that's much better :+1:
