### ISSUE TITLE
UP arrow is missing.

### ISSUE THREAD

**Issue by Maxxxxxx** [duckduckgo/duckduckgo#206]
I don't see any word about this anywhere.
I reinstalled or re-added DDG to home page, search bar, and address bar.  I return to DDG when in a website that has too much history.  On no DDG pages is the arrow to return to the top of the page present.

Do I re-add the add-on or is there a way to fix it?

Thank you.

**Comment by moollaza** [comment]
@Maxxxxxx thanks for reporting, can you give us more details about your OS and Browser?

The Arrow is  working for me right now.

**Comment by Maxxxxxx** [comment]
Now it's not again.
Windows 10 and Firefox.
New installation Win10.
Every other installation changes many features and views.

Thank you.

**Comment by Maxxxxxx** [comment]
Why did you close it without posting a solution?
I haven't seen it - the return to top UP arrow - in over a week (again) and it makes me nuts.

Nothing else has changed except another sixteen re-installations of Win10.
Thank you.
