### ISSUE TITLE
Broken link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Pnoexz** [duckduckgo/duckduckgo#207]
Under the header **Submitting a Bug or Suggestion** the link to _issues_ is broken.

Useful links:

CONTRIBUTING.md on github: https://github.com/duckduckgo/duckduckgo/blob/master/CONTRIBUTING.md

The link I believe it should be replaced with: https://github.com/duckduckgo/duckduckgo/issues/

Commit that broke the link: https://github.com/duckduckgo/duckduckgo/commit/b7001f5e5b2f6792c460c2c59a0a09d36d7ad605#diff-6a3371457528722a734f3c51d9238c13

**Comment by GuiltyDolphin** [comment]
@Pnoexz Thanks for the heads up!

Would you like to create a PR to fix this? We'd welcome the contribution :)

**Comment by waseem18** [comment]
@GuiltyDolphin I guess PR #192 resolves this issue.

**Comment by zekiel** [comment]
fixed!
