### ISSUE TITLE
Search results should have pagination option

### ISSUE THREAD

**Issue by Che234** [duckduckgo/duckduckgo#211]
Greetings hope you are well

I write because it seems to me that it would be more easy for users to have pagination (paging by numbers). This is because with the "loading more" at the bottom of the screen it becomes tedious to scroll, especially when the user goes through many search results. In addition, it's awkward having to scroll right back to the top of the search list, whereas clicking on a page number would take you there straight away.

Just continue to do an excellent job :)
### Original Spanish:

Saludos espero esten bien

Les escribo porque me parece que seria mas facil para el usuario con una paginacion por numeros porque el tenerlo asi, con el «cargando mas» al terminar el scroll, se vuelve tedioso en especial cuando ya el usuario lleva muchos resultados de busqueda y tambien el echo de que si me quiero regresar al principio de la busqueda tengo que darle al scroll hasta la parte de arriba pudiendole dar un clic a un numero y listo.

Igual sigan haciendo un excelente trabajo :)

**Comment by tagawa** [comment]
Hola @Che234. Gracias for the suggestion. I've tried to put it in English as well.

By the way, we have two alternative versions of DuckDuckGo:
https://duckduckgo.com/html/
https://duckduckgo.com/lite/
Both of these have proper pages and "next", "previous" buttons - perhaps that would be more convenient for you.

**Comment by moollaza** [comment]
Closing. This is off-topic for this repo, and not a problem we can currently solve.
