### ISSUE TITLE
Links within Instant Answer not navigable with keyboard

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/duckduckgo#212]
For example, a search query such as https://duckduckgo.com/?q=andy+murray&ia=about shows the Wikipedia Instant Answer, but the up/down arrow keys only navigate through the organic results. There's no way to open the IA links with the keyboard.

**Comment by moollaza** [comment]
Closing as off-topic. We can't solve that problem in this repo as it's related to our internal JS

**Comment by evenicoulddoit** [comment]
Is there a repo in which *it is* appropriate to raise this?
