### ISSUE TITLE
Logo not displayed correctly

### ISSUE THREAD

**Issue by gautamkrishnar** [duckduckgo/duckduckgo#213]
In https://duckduckgo.com/newbang page i think that there must be a little more spacing under the logo:
![screenshot 77](https://cloud.githubusercontent.com/assets/8397274/16830145/ae89306a-49ba-11e6-9f99-2fa25af4d9d3.png)

**Comment by zekiel** [comment]
thanks for the heads up @gautamkrishnar Looks like this is broken on a few static pages: 

https://duckduckgo.com/newbang
https://duckduckgo.com/api

We're on it!

**Comment by waseem18** [comment]
@zekiel I would like to work on this bug.

**Comment by bsstoner** [comment]
This has been resolved.
