### ISSUE TITLE
Text in the "Places" IA is reversed on FF 47/Ubuntu 15.10 (64-bit)

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/duckduckgo#214]
As [reported in the forum](https://duck.co/forum/thread/22577/places-text-on-ddg-is-rendered-backwards-on-fire), the latest Mozilla browsers display text in the "Places" IA from right-to-left on Ubuntu 15.10 (64-bit):

![ia-places-reverse-text](https://cloud.githubusercontent.com/assets/94173/16838672/6a8d48c4-4a05-11e6-8a39-a7def256b20f.png)

**Comment by nilnilnil** [comment]
This is in our internal bug tracker already.
