### ISSUE TITLE
Search error? 

### ISSUE THREAD

**Issue by jorgesumle** [duckduckgo/duckduckgo#216]
Tried to search \89PNG and got directly to http://www.gardenofpraise.com/pdf/childwk89.pdf. Sorry, I don't know if this is the right place to submit search errors, but there are so many duckduckgo related repositories.

**Comment by GuiltyDolphin** [comment]
Thanks @jorgesumle!

This appears to happen with various strings of `\89...`, I'll ping the team.

**Comment by GuiltyDolphin** [comment]
Just heard back from the team, `\` is the "I'm feeling ducky" shortcut (news to me!) - your query should work if you wrap it in double quotes.
