### ISSUE TITLE
Blank cheat sheet name returns Ace Editor cheat sheet

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/duckduckgo#217]
## Steps to reproduce:
1. Search for "cheat sheet": https://duckduckgo.com/?q=cheat+sheet&ia=cheatsheet
2. Check the IA that appears.

## What should happen:
There should be no Instant Answer displayed.

## What actually happens:
The Ace Editor cheat sheet is displayed. It looks like the platform is looking for a cheat sheet with a blank name, can't find one so picks the first one it finds (Ace Editor).

**Comment by moollaza** [comment]
This actually belongs in the Goodie repo 👍 

Reopening https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3517
