### ISSUE TITLE
How can I deploy DDG Instant Answers on my own search engine project?

### ISSUE THREAD

**Issue by nepsilon** [duckduckgo/duckduckgo#218]
I built a simple search engine for fun and would like to augment it with DDG Instance Answers.

I also saw the API available, but it doesn't provide the Instant Answers (or a very small number).

**Comment by GuiltyDolphin** [comment]
@nepsilon Not all Instant Answers are available through the API - most Spice won't be as it would be a violation of the TOS to re-distribute their results through our API.

Most Goodies ***should*** be available via the API as they use Perl packages for their main functionality which are often licensed under Free licenses that do not restrict such things.

I believe FatHeads should be too, as they don't use restricted material - I'm not sure about LongTails though.

Were there any particular Instant Answers you had in mind?

**Comment by nepsilon** [comment]
@GuiltyDolphin Thanks for the prompt reply. 

I'm interested in the currency conversion, weather, the cheat sheets, abbreviations, air flight info, air quality index and most of the programming/sysops related Instant Answers.

Do you maybe know about any open source (MIT or BSD licensed) similar API, or software?

**Comment by GuiltyDolphin** [comment]
@nepsilon I think Currency Conversion, Weather, Abbreviations, Air* etc. are all Spice, Cheat Sheets are Goodies, but the display is handled by a 'parent' Instant Answer so the same information won't be present, the programming/sysops are likely FatHeads, which should be available.

I'm not aware of any other similar APIs, usually APIs are focused on one area and won't provide broad results. I'll let you know if I come across anything though.

**Comment by nepsilon** [comment]
@GuiltyDolphin Got it. Thanks Ben 👍
