### ISSUE TITLE
Redirect when searching for a Perl regex

### ISSUE THREAD

**Issue by isislovecruft** [duckduckgo/duckduckgo#223]
When I go to https://duckduckgo.com or http://3g2upl4pq6kufc4m.onion/html/ and search for the string `perl (?!.....)`, I am redirected to http://www.dotdotduo.com/search/view/perl_%28%3F.

I'm not sure if this is the correct place to file this bug, please let me know if I should do otherwise.

**Comment by moollaza** [comment]
@isislovecruft it looks like this has been fixed? I'm unable to reproduce that behaviour.

**Comment by nilnilnil** [comment]
I can't either. Thanks for the report though. @isislovecruft are you still seeing this?

**Comment by isislovecruft** [comment]
Hmm. Do you both use Chome/Chromium? I'm still seeing this in both vanilla Firefox and Tor Browser. I just tested again in a brand new Fedora 24 VM, with a fresh copy of Firefox:

![snapshot107](https://cloud.githubusercontent.com/assets/907241/21332398/e7259eac-c63f-11e6-9f2f-6a25514a18d4.png)
![snapshot108](https://cloud.githubusercontent.com/assets/907241/21332420/131e0260-c640-11e6-9838-acd51942c83c.png)
