### ISSUE TITLE
Up Arrow is STILL MISSING

### ISSUE THREAD

**Issue by Maxxxxxx** [duckduckgo/duckduckgo#224]
I reinstalled Win10 after a massive repair marathon the third week of July.
Since installing Firefox (now v 49.0), I have never had the green (return to top) arrow.
I reinstalled FF (48.0.2) two days ago - or yesterday  - to see if a new browser download would make any difference; it did not.

After an OS installation, I add the same programs back to Firefox - WOT, HTTPS, Adblock/+ Element Helper, FEBE, Saved Password, + DDG.  In the beginning - July 22 onward, I disabled or enabled DDG a few times - (the add-on itself), although I always had DDG as my default search engine.   I noticed the other day that there is WOT setting on DDG - and the default if off.  I turned it on.  I do not now have two WOTS on my search page.   Nothing that I do makes any difference.  I can't believe I have put up with this for two months.  

I save a few different settings and retrieve them by typing in my search bar.  I also open DDG using my keyboard key.  Within the parameters I mentioned above I have a few different configurations, but nothing I have shows me the UP Arrow.  

When I get frustrated, which is at least once a day, I simply pound my keyboard with the heel of my hand, so I don't do any damage.

You have to be somewhat technologically sophisticated to navigate GitHub, so I don't come here too often.  I hope I get an email notice this time.

 Last time it healed itself, which was good since nobody posted a solution or bug fix,  
Having waited two months this time, I am hoping we can either fix DDG or tell me how to restore an excellent function.

Thank you for your help. 

![ddg - no green arrow](https://cloud.githubusercontent.com/assets/10837831/18803762/03a813ca-81a8-11e6-9d1e-5651d2b520ac.jpg)

**Comment by moollaza** [comment]
@Maxxxxxx I believe this is now resolved? We had spoken over email a few weeks ago 👍

**Comment by Maxxxxxx** [comment]
We absolutely did, Zaahir,


 Happy Holidays!


Thank you for your follow-up.




________________________________

**Comment by Maxxxxxx** [comment]
Acchhhh.  Again.

Edited content.

Thank you.
