### ISSUE TITLE
[FR: Bug de redirection après lancement de recherche DuckDuckGo] [EN: redirection bug after launching DuckDuckGo search]

### ISSUE THREAD

**Issue by smoine** [duckduckgo/duckduckgo#225]
French
--------
Description:
Un bug s'est produit sans afficher le résultat de la recherche DuckDuckGo et passe directement dans un autre site d'un autre langue.

Détail supplémentaire:
Je ne connais pas la signification d'un point rouge `\ufeff` dans le développeur Web de Mozila firefox donc je passe à la recherche d'une information de `\ufeff` en ajoutant la simplifier la réduit le nombre de recherche de la source `Mozilla firefox` et afficher en français.

Procédure de bug:
1. Site DuckDuckGo [https://duckduckgo.com/]
2. Taper dans la recherche `\ufeff Mozilla firefox`
3. Directement dans un autre site d'un autre langue.

Résultat de bug:
Il affiche directement avec redirection sans afficher la liste de la recherche trouvé et passe directement d'un autre site de l'autre langue.

Configuration:
J'utilise un système de bureau Gnome 16.04 et navigateur Mozilla Firefox 49.0

English
-----
Description:
A bug occurred without displaying the search result DuckDuckGo and goes directly into another site in another language.

Additional details:
I do not know the meaning of a red dot `\ufeff` in the Web developer Mozila firefox so I spend looking for information of `\ufeff` and adding simplify reduced the number of source search `Mozilla firefox` and display in french.

Bug procedure:
1. Site DuckDuckGo [https://duckduckgo.com/]
2. Tape in the search `\ufeff Mozilla firefox`
3. Directly into another site in another language.

Bug result:
It displays directly with redirection without showing the search list found and brought directly to another site the other language.

Configuration:
I use Gnome 16.04 desktop system and browser Mozilla Firefox 49.0

**Comment by mintsoft** [comment]
@moollaza I've just confirmed this on Win7 + FF 50.0a2; also on Vivaldi; I'm guessing there's some bang-style thing going on the BOM (`\ufeff`) there?

**Comment by moollaza** [comment]
@mintsoft yes the `\` is the shortcut to follow the first result -- we may need to add a check to see if the \ is part of a unicode string.

**Comment by moollaza** [comment]
This is technically the expected behaviour, though I do agree it is very misleading.

**Comment by moollaza** [comment]
Quoting the word with the `\` prevents the auto-redirect:

["\ufeff" Mozilla firefox](https://duckduckgo.com/?q="%5Cufeff"+Mozilla+firefox)
