### ISSUE TITLE
Jump to first result when pressing `tab`

### ISSUE THREAD

**Issue by LeonardLaszlo** [duckduckgo/duckduckgo#226]
Hi there!

I suggest the search engine to be more optimized for keyboard usage. It would be great if the "selector" jumps to the first result of the search when I hit `tab` key.

Thanks for this great search engine!

**Comment by moollaza** [comment]
@LeonardLaszlo thanks for the feedback. This isn't exactly the correct place for this kind of feedback. This repo is related to our open source Instant Answer platform. The behaviour you're describing would need to be handled internally.

Would you mind sending this along by clicking the "Send Feedback" button at the lower right hand side of results page.

Alternatively you can visit https://duckduckgo.com/feedback

Thanks again!
