### ISSUE TITLE
location to report issues

### ISSUE THREAD

**Issue by devanshdalal** [duckduckgo/duckduckgo#232]
Hi

I am not sure where are bugs for the search engine https://beta.duckduckgo.com/?q=&t=hs and https://duckduckgo.com/?q=&t=hs repoted? I have a bug in mind in the beta site. 

Anyways doing it here:

To reproduce the bug, go to the [link](https://beta.duckduckgo.com/?q=bug+reporting&t=hs&ia=web). Then try to clear the country filter by clearing the country flag. Page just refreshes with the country's flag there as it was, without clearing the filter?

**Comment by moollaza** [comment]
> I am not sure where are bugs for the search engine https://beta.duckduckgo.com/?q=&t=hs and https://duckduckgo.com/?q=&t=hs repoted? I have a bug in mind in the beta site.

@devanshdalal The best way to report bugs related to main site is by clicking the  "Send Feedback" button on the page. 

> To reproduce the bug, go to the link. Then try to clear the country filter by clearing the country flag. Page just refreshes with the country's flag there as it was, without clearing the filter?

I'm unable to reproduce this -- what browser/OS are you using?

More importantly, does this occur on the main duckduckgo.com site? Beta is only intended for use by DuckDuckHack developers and is not guaranteed to be kept up to date with the main site.
