### ISSUE TITLE
DDG/Chrome/Android add to homescreen nag

### ISSUE THREAD

**Issue by dredmorbius** [duckduckgo/duckduckgo#235]
This is showing up constantly on android. I'd much prefer it didn't.

(No idea where to request this, please point to right repo if this isnt it.)

**Comment by moollaza** [comment]
@dredmorbius please set start.duckduckgo.com as the URL for your homepage and you will no longer see the "Add to browser" modal.

Apologies for the inconvenience!

**Comment by dredmorbius** [comment]
It _is_ set in Chrome/Android.  But the nag still appears when going to Incognito mode.

Realise that with Incognito, cookies are not a reliable test.  You might want to consider other mechanisms, possibly randomising appearance of the nag, or timing out by IP (with appropriate tracking protections -- there are hash filter algos which might work for that), etc.

This shows up _all the time_. You've already got me.  This is how you start losing me.

On February 7, 2017 8:04:43 PM CST, Zaahir Moolla <notifications@github.com> wrote:
>@dredmorbius please set start.duckduckgo.com as the URL for your
>homepage and you will no longer see the "Add to browser" modal.
>
>Apologies for the inconvenience!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/duckduckgo/duckduckgo/issues/235#issuecomment-278207098

-- 
Krell Power Systems Unlimited. When you need unlimited power, go to Krell!

**Comment by moollaza** [comment]
@dredmorbius apologies, I didn't realize you're using incognito mode. If you're using star

**Comment by moollaza** [comment]
@dredmorbius to confirm, is it the button below the search box on our home page that you'd like us to remove?

Or are you referring to something else?

![bs_realdroid_mobile_google nexus 6-5 0-1440x2560](https://cloud.githubusercontent.com/assets/873785/22754699/72c220a2-ee0e-11e6-96a6-1bacdc78a146.jpg)

**Comment by dredmorbius** [comment]
@moollaza No, that button is fine.

I'm referring to what appears to be either an Android pop-up notification or a Chrome one, much larger, across the bottom of the screen.  I'll capture a screenshot next time I see it.

To be clear, the screenshot here showing my device view is **not** the problem, this would be acceptable (though again, useless as I've already got DDG as much a default as possible).
![screenshot_2017-02-11-15-51-15-1](https://cloud.githubusercontent.com/assets/5445858/22857811/7ab7530c-f072-11e6-842d-5d303fa5ec9c.png)

**Comment by dredmorbius** [comment]
Here we are, this guy.  Appeared after closing all Incognito tabs, then opening up DDG again.
![screenshot_2017-02-11-16-09-25-1](https://cloud.githubusercontent.com/assets/5445858/22857904/a942c812-f074-11e6-88db-11651fbd518e.png)

**Comment by moollaza** [comment]
@dredmorbius sorry for the delay here -- we don't have a solution yet, but this is something we're aware of and currently working on fixing.

Apologies for the inconvenience.

**Comment by dredmorbius** [comment]
Thanks, appreciate the ack and update.  It's not a showstopper, but it's decidedly annoying.

On March 6, 2017 10:09:41 PM CST, Zaahir Moolla <notifications@github.com> wrote:
>@dredmorbius sorry for the delay here -- we don't have a solution yet,
>but this is something we're aware of and currently working on fixing.
>
>Apologies for the inconvenience. 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/duckduckgo/duckduckgo/issues/235#issuecomment-284616391

-- 
Krell Power Systems Unlimited. When you need unlimited power, go to Krell!

**Comment by nilnilnil** [comment]
@moollaza can you add me to the Asana task?

**Comment by moollaza** [comment]
> can you add me to the Asana task?

done.

**Comment by dredmorbius** [comment]
NB:  I haven't seen the nag in quite some time.  Fixed?

(Alternatively: the fact that Google Chrome now allows DDG to be set as a default search engine means I'm hitting the DDG homepage far less frequently.)
