### ISSUE TITLE
broken redirects

### ISSUE THREAD

**Issue by rhazor** [duckduckgo/duckduckgo#237]
duckduck is showing dead 404 redirects when searching these two websites: junodownload.com and juno.co.uk

E.g. https://duckduckgo.com/?q=house+site%3Ajunodownload.com&atb=v49-4&ia=web all LINKS DEAD

To fix, each time you need to remove 'secure' from the URL to load the page.

Why is DuckDuck linking to dead URLs, even to new and fresh pages, every week.

**Comment by moollaza** [comment]
@rhazor thanks for reporting. I've asked the team to investigate.

FWIW, please report future bugs related to the results through the FEEDBACK button on the search results page. This repository is unrelated to the link results on DuckDuckGo.com
