### ISSUE TITLE
DDG/Crome/Android add to homescreen nag:  Suggested fix isn't

### ISSUE THREAD

**Issue by dredmorbius** [duckduckgo/duckduckgo#238]
I'd previously opened #235.  The issue has been closed though the suggested fix doesn't work.

I'm using Chrome/Android, frequently in Incognito mode (because: reasons).  Though DDG is set as my homepage (it _cannot_ be set as the default search engine -- a Chrome fault), this nag appears constantly in Incognito.

Note that 1) use of Incognito may be increasing for privacy reasons and 2) standard tests of state such as cookies will not be persistant.  I'd recommend randomisation of the nag, use of an anonymity-preserving mechanism for avoiding frequent re-nagging (say, a bloom filter) based on IP, or other mechanisms of avoiding this.

You've already got me on DDG.  This is  how you lose me.

**Comment by moollaza** [comment]
@dredmorbius apologies. I've re-opened #235, we can continue the discussion there.
