### ISSUE TITLE
DuckDuckHack on The Changelog!

### ISSUE THREAD

**Issue by jerodsanto** [duckduckgo/duckduckgo#239]
Howdy from [The Changelog](https://changelog.com/podcast)!

We'd love to have you on the show sometime soon. Who would be best person to join us to talk about DDG and all the cool stuff y'all are up to?

_(If you haven't heard of The Changelog, it's a weekly conversation that gets to the heart of open source technologies and the people who create them.)_

Please email editors@changelog.com to coordinate. Looking forward to talking to y'all!

**Comment by tagawa** [comment]
Thanks for the message! I've sent an email to the above address.
