### ISSUE TITLE
Back to Top - Missing Arrow - New Issue

### ISSUE THREAD

**Issue by Maxxxxxx** [duckduckgo/duckduckgo#240]
Firefox 52.0/Win 10

Before this issue recurred, there was an Adblock Plus filter called "Back to Top."  I had to manually disable it every time that I opened a new search page.  (As I work from home, I am on the computer for hours and hours, so I search and close SEs all day long.)

I added a new filter to the Adblock Plus exceptions page (###back-to-top).  Then somebody had me change the filter to duckduckgo.com###back-to-top.  It never worked.  I have three lists of exceptions, which I presume are related to the different lists (Easy List, Easy Privacy, Fanboy's - etc.)  The people at the ABP forum never give me the tools to figure out ABP myself, so over the ten or eleven years, I understand vaguely how it works, but details elude me.  Inside the filter preferences on ABP, it (the added exception) has never changed its font color to the same color font on the exceptions page - it sticks out like a sore thumb, in black.  See attachment #1. (DDG - Back to Top)

Something changed - I not only lost the up arrow (return to top) on DDG;  it is not present on ABP Open Blockable Items, I don't see a new or old iteration on its filter lists, and my added filter has a perennial hit list with a count of -0- hits.  

 My biggest obstacle when not knowing who is responsible for this, is finding out who can help me restore the UP ARROW.  Attachment #2 (No Back to Top Arrow)

Thank you. 

![ddg - back to top](https://cloud.githubusercontent.com/assets/10837831/23872251/cb55aa90-07ea-11e7-9e0c-4050fd34f8ca.jpg)
![no back to top arrow](https://cloud.githubusercontent.com/assets/10837831/23872258/d03537f6-07ea-11e7-8e58-2a49293cfd32.jpg)

**Comment by moollaza** [comment]
@Maxxxxxx we have actually removed the "Back to Top" button from the page -- it's not being removed by your AdBlocker.

I have alerted the team to your feedback.

An alternative way to scroll to the top (or the bottom) of the page is using the "PageUp" and "PageDown" keys on your keyboard. Apologies for the inconvenience!

**Comment by Maxxxxxx** [comment]
Zaahir,


Why in the world would you do that - were there unintended consequences?


I love that feature about DDG.

No other search engines use it.


There are codes to add it to your personal website - but not to your search engine.

Are there safe alternatives?

However, I will definitely try the PageUp and PageDown buttons.


Thank you for your immediate response.




________________________________
