### ISSUE TITLE
Upvoting directly in the search results ?

### ISSUE THREAD

**Issue by vsraptor** [duckduckgo/duckduckgo#246]
http://stackoverflow.com/questions/43418856/duckduckgo-and-stackoverflow

**Comment by moollaza** [comment]
Thanks for the suggestion, however, we don't have any plans to anything like this in the near future.

Implementing this would mean we'd have to allow users to log in to StackOverflow from DuckDuckGo which means dealing with authentication, etc.

I'm not even sure if this would be possible while maintaining our privacy policy.
