### ISSUE TITLE
Feature request: Add countdown to <date-time string>

### ISSUE THREAD

**Issue by bogas04** [duckduckgo/duckduckgo#249]
This would be a cool addition IMO. I'd love to work on the same, though i'll need some help to get started!

**Comment by pjhampton** [comment]
Hey @bogas04,

Thanks for the idea! 😄  Unfortunately, you're in the wrong repo and [hasn't met the community expectations of opening an issue](https://duckduckhack.com/contributing.html). 

Please reopen this in the Goodies repo quoting the Timer IA

**Comment by ManrajGrover** [comment]
@bogas04 Here is the repo [link](https://github.com/duckduckgo/zeroclickinfo-goodies) 😄

**Comment by moollaza** [comment]
We already have a countdown to date IA 👍 

https://duck.co/ia/view/countdown

**Comment by bogas04** [comment]
> We already have a countdown to date IA :+1:

Amazing, would be cool if it also works for "count down"
