### ISSUE TITLE
Doesn't exclude URL

### ISSUE THREAD

**Issue by egeesin** [duckduckgo/duckduckgo#250]
When I type 'google -twitter', it's working. However, when I exclude a site: 'google -site:twitter.com', it says 'Showing results excluding: twitter.com' but on the contrary, only shows results from twitter.com.

**Comment by vallode** [comment]
I tried replicating your problem but for me searching using the terms `google -site:twitter.com` worked as intended: removing any links to twitter.com

Not sure how else to approach it. Hope we can resolve it!

**Comment by moollaza** [comment]
We've recently been working on our search filters/syntax. It looks like this has been fixed 👍
