### ISSUE TITLE
Suggestion : Can we show comparision between two hex codes? 

### ISSUE THREAD

**Issue by Logan1x** [duckduckgo/duckduckgo#251]
Mostly web developer use hex values to compare different colors and when we put hex in search bar we get color but i tried to compare two hex code that is not working for any search engine. So we should add this.

![screenshot from 2017-07-08 16-54-11](https://user-images.githubusercontent.com/10944610/27984860-29f2f5b6-63fe-11e7-8345-7a58713367dd.png)

but when i tried to compare  two hex codes

![screenshot from 2017-07-08 16-53-56](https://user-images.githubusercontent.com/10944610/27984862-383886a4-63fe-11e7-8296-813aa8700c38.png)

**Comment by naqe** [comment]
whats the difference between x and z?

**Comment by Logan1x** [comment]
@naqe  x and z ??

**Comment by J-tt** [comment]
This is the wrong repo, please use the 'Create Issue' button on: https://duck.co/ia/view/color_codes

@pjhampton Sorry for tagging you, but this should be moved/closed
