### ISSUE TITLE
Using Jenkins for DuckDuckGO CI/CD

### ISSUE THREAD

**Issue by yoginth** [duckduckgo/duckduckgo#256]
Rather than using **Travis CI** for Testing **@duckduckgo** can Implement both **_CI & CD_** in **Jenkins**.

I'm here to implement things with **Jenkins**.

**Comment by moollaza** [comment]
@yoginth thanks for the suggestion. We're happy with Travis though, it works fine and costs us nothing.

**Comment by yoginth** [comment]
ok!
