### ISSUE TITLE
!w typesystem searches on norwegian wikipedia

### ISSUE THREAD

**Issue by pietervdvn** [duckduckgo/duckduckgo#257]
Hi team,

In a very weird bug, typing `!w typesystem` routes me to https://no.wikipedia.org/wiki/Special:Search?search=typesystem&go=Go&searchToken=9be9l8t9hcle0q8jyzamo5ijw.

All other searches correctly route to `en.wikipedia.org/...`

Tested on Ubuntu 16.04, firefox 55.0.2 (64-bit), with and without private navigation.

Feel free to ask more questions

**Comment by moollaza** [comment]
I'm unable to recreate this, using Firefox on Mac.

Do you happen to have a region boost enabled? Does this happen in other browsers? Have you tried disabling extensions?

**Comment by pietervdvn** [comment]
What is a region boost? My 'belgium search results' are disabled by default.

This also happens on my chromium browser,  my Android (Firefox Focus,
LineagOS) and my mothers Samsung Android (Samsung Browser). Please note
that this only happens with the word "typesystem" (if searched without
double quotes); while other words correctly route me to the English
wikipedia.




Met vriendelijke groeten,
Pieter Vander Vennet

2017-08-30 17:58 GMT+02:00 Zaahir Moolla <notifications@github.com>:

**Comment by dnivi3** [comment]
Can confirm this issue. Tried with Chromium and TorBrowser with a clean identity and IP address. Both lead to the Norwegian Wikipedia search results.

**Comment by moollaza** [comment]
@pietervdvn @dnivi3 thanks, I'm now seeing this behaviour.

@mrshu any ideas what's going on here?

**Comment by preemeijer** [comment]
I think this is not a bug or something. 
Explanation:
 * https://duckduckgo.com/?q=wikipedia+typesystem&t=hb&ia=web

The only Wikipedia entry that is shown with typesystem is "da" and "no" Wikipedia.
The first search is for the English Wikipedia but is "type system".
If you search as follows !w type system it works. I just think there is no entry for typesystem in the English wikipedia (without the space).

**Comment by moollaza** [comment]
@preemeijer good find.

@pietervdvn if you add a redirect on Wikipedia.com for "typesystem -> type system" the bang should behave as you expect.

I believe that's the simplest solution here.
