### ISSUE TITLE
Please add DuckDuckGo Beta to AMO

### ISSUE THREAD

**Issue by davidhedlund** [duckduckgo/duckduckgo#258]
There are many search engines submitted to [AMO](https://addons.mozilla.org/en-US/firefox/search/?q=DuckDuckGo&appver=&platform=linux).

Can you please add [DuckDuckGo Beta](https://beta.duckduckgo.com/)?

**Comment by J-tt** [comment]
I added it into my forked extension as a search option.

See https://github.com/j-tt/firefoxwe-zeroclickinfo

**Comment by davidhedlund** [comment]
@J-tt Great.

**Comment by J-tt** [comment]
@pjhampton This looks like it could be closed now

**Comment by davidhedlund** [comment]
@J-tt No. I opened this issue because I'm asking https://addons.mozilla.org/en-US/firefox/user/duckduckgo/ to release it on addons.mozilla.org (AMO).

**Comment by J-tt** [comment]
Due to the current status of DuckDuckHack, and the fact that solutions already exist it seems unlikely.

This is also the wrong repo to create this issue in, as it's more focused on the internal code, and less on new features/extensions.

**Comment by davidhedlund** [comment]
@J-tt Ok, where should I submit it then?

**Comment by J-tt** [comment]
Since it would be a new project, and not an existing one, try either the [subreddit](https://www.reddit.com/r/duckduckgo/), or the [dev mailing list](https://www.listbox.com/subscribe/?list_id=197814).

**Comment by pjhampton** [comment]
Thanks @davidhedlund and @J-tt 
I agree with @J-tt. Please submit to the subreddit or via the SERP to grab the attention of DDG employees.

**Comment by davidhedlund** [comment]
@J-tt @pjhampton Thanks, I requested it here: https://www.reddit.com/r/duckduckgo/comments/6y0a1b/please_add_duckduckgo_beta_opensearch_engine_to/

**Comment by moollaza** [comment]
@davidhedlund @J-tt to clarify, the "Next" extension linked above points to next.duckduckgo.com, which we used before we launched the current design to get feedback. Currently, it is not in use and there is nothing special about that link anymore.

Beta.duckduckgo.com was intended to be used only by DuckDuckHack developers, to test new Instant Answers. Seeing as DuckDuckHack has now entered maintenance mode, there will be nothing new appearing on the beta.duckduckgo.com, so there's no need to have an extension that allows you to search there.

**Comment by davidhedlund** [comment]
@moollaza Thank you for explaining.

**Comment by davidhedlund** [comment]
OpenSearch add-ons are [deprected on addons.mozilla.org](https://blog.mozilla.org/addons/2019/10/15/search-engine-add-ons-to-be-removed-from-addons-mozilla-org). However, it's still possible to add search engines in Firefox. For example, if you visit https://duckduckgo.com/html/ you add it as described on the screenshot:

![Untitled](https://user-images.githubusercontent.com/6416073/73594432-bfec1400-450e-11ea-95ab-596aece49368.png)

It's because the site has this HTML: `<link title="DuckDuckGo (HTML)" type="application/opensearchdescription+xml" rel="search" href="/opensearch_html.xml" />`

Can you please add `<link...` to these sites?:
* https://next.duckduckgo.com/
* https://beta.duckduckgo.com/
