### ISSUE TITLE
Currency conversions IA not serving up-to-date data

### ISSUE THREAD

**Issue by dnivi3** [duckduckgo/duckduckgo#259]
The currency conversions IA is for some reason serving up conversion rates that are outdated. Specifically, it seems to pull the conversion rates for `Mid-Market Rates: 2016-07-21 at 16:49 UTC` instead of current rates. 

Try https://duckduckgo.com/?q=1+EUR+in+USD for an example. Screenshot below. 

![screen shot 2017-09-01 at 11 03 22](https://user-images.githubusercontent.com/1163576/29963084-e6ce58e2-8f05-11e7-824a-a78ee3d51558.png)

**Comment by pjhampton** [comment]
Thanks @dnivi3. This is in the wrong repo. Moving it to the Spice repo

**Comment by pjhampton** [comment]
This should now be fixed 👍
