### ISSUE TITLE
W3C

### ISSUE THREAD

**Issue by legagneur-matthieu** [duckduckgo/duckduckgo#260]
Hello guys !

first i'm french so sorry for my bad english and again I sorry but I can't commit by myself a fix because I don't know what's file I must change ( the project is big and y knew DDG very recently)

Just one litle thing about the HTML code of DuckDuckGo.com : 
I have test https://duckduckgo.com in the W3C validator,
(https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fduckduckgo.com)
you have 5 errors : 

- The first, the subtag "lang" in the html tag don't use the new standard : 
(https://www.w3.org/International/articles/language-tags/)

- the second, the tag : 
"< meta http-equiv="content-type" content="text/html; charset=UTF-8;charset=utf-8">" 
should be replace by simple : "< meta charset="UTF-8">"

- the third, (and fourth), in the tag "< meta name="twitter:site" value="@duckduckgo">" 
the "value=" subtag must be change by "content="
(https://dev.twitter.com/cards/getting-started)

- the fifth : in the tag "< div id="" class="content-wrap--home">" you have a empty id subtag

that's not a important bug, but respect the W3C is a proof of quality.
Thanks for reading me and god save the duck ^_^

**Comment by moollaza** [comment]
Thanks for reporting. I've made a note of this internally. This repo isn't actually related to any of that code though so I'm going to close this as it will be tracked internally.
