### ISSUE TITLE
None of the results contain the phrase I entered

### ISSUE THREAD

**Issue by thany** [duckduckgo/duckduckgo#263]
Please consider this search:
https://duckduckgo.com/?q=umbraco+%22usync%22+%22An+error+has+occurred+-+undefined%22&t=ffab&ia=web

NONE of the results contain all the search terms.

It's better to display "no results" if there aren't any, than to provide nonsense results that I'm clearly not searching for.

**Comment by moollaza** [comment]
@thany thanks for leaving us feedback, however unfortunately this isn't the correct place. 

In the future if you need to leave use feedback regarding search result or something else you see on the search result page, please use the 'Feedback' button at the bottom right of the page. 

That will ensure your feedback is directed to the right people 👍 

I'm going to close this issue as it's unrelated to this repo, which is for our open source Instant Answers.
