### ISSUE TITLE
GitHub organization member request?

### ISSUE THREAD

**Issue by YoginthS** [duckduckgo/duckduckgo#267]
Hey,

I am really excited about the active development and wanted to be a part of the **Duck Duck Go** organization on GitHub. In this regard, how can I become a member and would love if somebody would add me to it?

My GitHub username is YoginthS

Thanks, Yoginth

**Comment by moollaza** [comment]
@YoginthS DuckDuckHack is currently in maintenance mode and so we are no longer accepting new Community Leaders.

Thanks
