### ISSUE TITLE
Do not assume a word was mistyped

### ISSUE THREAD

**Issue by toyprotector** [duckduckgo/duckduckgo#274]
That is, do not show results for "prion" when the query contains the word "prior" and does not contain the word "prion".

It is very irritating for a person trying to be precise when a search engine attempts to "correct" him.

![Screenshot_20200420-220332_Chrome](https://user-images.githubusercontent.com/63397258/79813741-de65ec80-8352-11ea-8405-cf55611b4161.jpg)

(Sorry if this is the wrong place.)

(On a positive note, your service is way better than Google. I'm just trying to help you make it better.)

**Comment by moollaza** [comment]
@toyprotector thanks for reporting this and sorry our results didn't match your expectations.

_(Sorry if this is the wrong place.)_

It is. The best way to report feedback is to used the "Feedback" button on the SERP. On mobile, you can click the sad or happy face in the side menu, which you can open by clicking the menu icon (3 horizontal lines) in the top right corner of your picture.

By reporting your feedback through there, the correct people will see it and be able to act on it.

I'm going to close this as the issues is unrelated to the code in the Repo.
