### ISSUE TITLE
So I have a question that I wanted to ask, are you guys using bing api for searches

### ISSUE THREAD

**Issue by Xyncgas** [duckduckgo/duckduckgo#276]
Words on the street u guys are doing it.
Which is deceiving how u tell people you don't track them and it's all private and stuffs, while u are acting as a proxy to anonymously routing people's searches to microsoft company, it's like you are asking a question to their search engine so it's safer but you never been transparent about it.
https://search.brave.com/ says your search engine doesn't have independent indexes so they must know something about u to say it

**Comment by tagawa** [comment]
Thanks for getting in touch. We actually get our search results from hundreds of sources (see [this help page](https://help.duckduckgo.com/duckduckgo-help-pages/results/sources/) for more info). Our goal with DuckDuckGo Search is to get you the best search results we can while maintaining your privacy, and we think the best way to do that is often to work with partners who specialize in those areas (e.g., DarkSky for weather). 

Search results in general now comes from dozens of distinct indexes, e.g., maps, knowledge graph, local results, and the traditional “10 blue links,” and you need all of them to function correctly and come up at the right times or people will leave (see [this comment](https://news.ycombinator.com/item?id=27528625) for more info on how search has evolved). Some of these indexes we run mostly ourselves (e.g., knowledge graph), and some we work with partners on (e.g., Bing for the traditional links), but in all cases we proxy requests such that loading our search results pages is anonymous and there are no search histories being created. Brave [actually](https://news.ycombinator.com/item?id=27597053) [isn’t](https://news.ycombinator.com/item?id=27593801) [that](https://twitter.com/pierrefar/status/1407402749273182217) [different](https://news.ycombinator.com/item?id=27594110).
