### ISSUE TITLE
Browser incompatability in Opera mini browser in Android based phone..

### ISSUE THREAD

**Issue by praveenjayaraj** [duckduckgo/duckduckgo#35]
I use an Android based phone with the screen resolution of 240*320. I use the Opera mini browser for browsing and i tried duckduckgo in it. But what i got was a page with just a text box in the top left corner and a button with green color on it and no text. I dont know whether it is a bug or it is incompatible with the browser..

**Comment by javathunderman** [comment]
@moollaza I assume this is still an issue then?

**Comment by psatish** [comment]
Opera Mini version 7.0.5.45389
Yes this has not been fixed
