### ISSUE TITLE
ddg_spice_test() doesn't function as documented

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/duckduckgo#39]
https://github.com/duckduckgo/duckduckgo/blob/master/lib/DDG/Test/Spice.pm#L77

As documented, this syntax should be legal, however it currently breaks.

**Comment by GuiltyDolphin** [comment]
Hey - just saw this after #205 - @moollaza do you reckon we can just remove `call_type` as a requirement then?

**Comment by moollaza** [comment]
> do you reckon we can just remove call_type as a requirement then?

Once the Spice -> Goodie conversion are done I don't see any real need for the `call_type` param...

**Comment by GuiltyDolphin** [comment]
@moollaza Sweet! That'll make things much nicer :)
