### ISSUE TITLE
Keyboard scroll causes wierd buggy scroll

### ISSUE THREAD

**Issue by bendtherules** [duckduckgo/duckduckgo#96]
Goto any search results page, press down key and hold.
What I see:
Page starts scrolling, result selection changes until it reaches the last result visible in the viewport, then somehow it scrolls up to the first result visible and then this thing continues in semi-infinite loop (scrollbar tends to move downward slowly after each iteration).

**Comment by moollaza** [comment]
Closing given how old this is. @bendtherules I assume this is no longer an issue?
